#!/bin/bash

# for i in $(find ../build/gcov -name "*.gc*")
# do
#     cp $i ${i##*/build/gcov/}
# done

# gcovr -o server/coverage_report.html -r server -u --html --html-details
# gcovr -o coverage_report.xml -r server -u --xml-pretty
# find server -name "*.gc*" -exec rm {} \;

# gcovr -d -o coverage_report.xml -r server -u --xml-pretty --object-directory ../build/gcov/server/

rm -rf covrep/*

lcov --rc lcov_branch_coverage=1 -c -b . -d build/gcov/ > ut_coverage.info
lcov -r ut_coverage.info '/usr/include*' '*/gtest/g*' > clean_ut_coverage.info
genhtml --rc genhtml_branch_coverage=1 clean_ut_coverage.info -o covrep/ --branch-coverage -f
# ../lcov2xml/lcov_cobertura.py ut_coverage.info -o ut_coverage.xml
rm ut_coverage.info